name: BOSH SLSA

on:
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  generate-slsa-provenance:
    needs: setup-environment
    permissions:
      id-token: write # For signing
      contents: write # For asset release.
      packages: write # For package upload.
      actions: read # For getting workflow run info.
    uses: dtimm/bosh-secure-supply-chain/.github/workflows/bosh_slsa.yml@main
